---
- rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  become: true

- get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: install the latest version of Java
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: true

- name: install the latest version of Jenkins
  yum:
    name: jenkins
    state: present
  become: true

- name: Start service jenkins, if not running
  service:
    name: jenkins
    state: started
  become: true

